jsonschema/_validators.py

Example:
```
>>> 150.0 % 0.01
0.009999999999996878
>>> 0.01 - 0.009999999999996878
3.1225022567582528e-15
>>> 150.0 / 0.01
15000.0
```
I've prepared a commit against json-schema/JSON-Schema-Test-Suite adding following test case:
```
{
"schema": {"multipleOf": 0.01},
"tests": [
{
"description": "150.0 is multiple of 0.01",
"data": 150.0,
"valid": true
},
{
"description": "150.0001 is not multiple of 0.01",
"data": 150.0001,
"valid": false
}
]
}
```
but am not sure it is the right place to put such test nor how to choose "better" values without relying on implementation (does implementatio use modulo ? on double or single precision ? etc). As a result, I could not come up with a meaningful description. Anyway, this test fails with current implementation with:
ValidationError: 150.0 is not a …

Improve mutlipleOf validator with floating point value.

---

README.rst

Just a personal pet peeve, feel free to ignore this PR: I like when clicking the Travis badge will get me to the Travis page, so I can check easily if the build failed for some bug in Travis or some bug in the code.

Add link to latest Travis build.

---

setup.py

The current universal wheels have static install_requires matching the python version they were built on: so a wheel built on 2.6 claims it needs argparse and repoze.lru on 2.7 and 3.4, etc. This clearly doesn't work :)
environment markers are however honoured by wheels and pip, using this somewhat ugly syntax in extras (I'm looking to improve that, but this works - see the distutils-sig list for some discussion on it recently).

Fix universal wheels

---

jsonschema/_validators.py
jsonschema/tests/test_validators.py

I have found very uncommon, but still a bug, with formatting error messages for unique items, when instance is a tuple.
Attached a test case to reproduce:
```
import unittest
from jsonschema.exceptions import ValidationError
from jsonschema.validators import Draft4Validator, validate
TEST_SCHEMA = {
'type': 'array',
'items': {
'type': 'number',
},
'minItems': 2,
'maxItems': 3,
'uniqueItems': True,
}
TYPES = Draft4Validator.DEFAULT_TYPES.copy()
TYPES['array'] = (list, tuple)
class Validator(Draft4Validator):
DEFAULT_TYPES = TYPES
class TestItemsErrorMessages(unittest.TestCase):
array_type = list
validator_class = Draft4Validator
def check_error_message(self, instance):
self.assertRaises(ValidationError,
validate,
instance,
TEST_SCHEMA,
self.validator_class)
def test_min_items(self): …
```

Fix formatting error for unique items if instance is a tuple

---

docs/faq.rst

The FAQ explains that one could (in theory) write a schema in which default values aren't valid under their own schema, and then goes on to present some example code that would allow such a use-case.
Fair enough, but I think most users would rather have an example that actually *does* validate the defaults.  Plus, if the default values are added to the instance *before* validation, then entire objects can be provided with default contents, even if the object was missing from the instance entirely.  (The updated FAQ text in this PR provides an example.)

docs: faq: Updates to extend_with_default() example

---

jsonschema/exceptions.py
jsonschema/tests/test_exceptions.py

https://github.com/Julian/jsonschema/issues/283

Minor fix in ErrorTree for multiple errors on different levels.

---

jsonschema/_validators.py
jsonschema/cli.py
jsonschema/tests/test_cli.py

When I try to validate a Draft3 schema using the Draft4 validator, you get the following error:
```
File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 299, in required_draft4
for property in required:
TypeError: 'bool' object is not iterable
```
My change _fixes_ this issue by alerting the use to the mis-match in draft versions.

Made required_draft4 more robust when used with Draft3

---

jsonschema/_format.py

If it was intentional to line up the functions for readability then disregard, but this actually hurt readability for me as the double indentation caught me off guard and my immediate thought was "that can't be right." Well TIL, just thought I'd propose this change in case this was an accident.

Fix indentation

---

.travis.yml
tox.ini

This will hopefully add Python 3.3, 3.4, and 3.6 testing as well as
simplify the travis management via the tox-travis tool.

Improve travis and tox build

---

jsonschema/validators.py

Instead of flattening to find out `is_number`, we can just check `issubclass(int, pytypes)` which doesn't require flattening the types list. Only if that passes do we need to look further.

perf: Make is_type faster and cleaner

---

setup.py

Hi,
I'm using your library (cool, thanks!) and I'm migrating my project to using [pipenv](https://docs.pipenv.org/) instead of pip.
Pipenv [has a bug](https://github.com/pypa/pipenv/issues/1279#issuecomment-364623908) that prevents to correctly parse the old `extra_requires` syntax. Apparently this syntax is old and superseded by `install_requires`.
In short, what happens is that in my py3 virtualenv, pipenv wrongly installs `functools32` and that breaks the whole package installation process. 
This patch allows me to use `jsonschema` in my project migrated to pipenv.
I'd be happy to have your opinion on this small patch, thanks!

Update setup.py syntax for pipenv (bug) compliancy

---

jsonschema/tests/test_validators.py
jsonschema/validators.py

Importing requests takes well over 100ms and is used only for resolving refs from remote URIs - move the import to runtime.
--
Hopefully the test case modification is ok too - mocking a runtime import was not something I've done before :) If there is more elegant or "industry standard" solution, please let me know, and I'll fix it.

Move requests import to runtime

---

docs/spelling-wordlist.txt
jsonschema/tests/test_validators.py
jsonschema/validators.py

Fix another spot where 'id' vs. '$id' needs to be handled for draft 6+.
Signed-off-by: Grant Likely <grant.likely@arm.com>
[robh: re-word commit message]
Signed-off-by: Rob Herring <robh@kernel.org>

Handle $id property for draft6 in validates()

---

jsonschema/tests/test_validators.py
jsonschema/validators.py

Alternative solution to #417 (fixes #417) 
Currently, the validator registration is hardcoded to use the deprecated "id" keyword, rather than using the new "id_of" function passed to `create`. This means that only draft 3 and 4 are currently registered. This is not visibly a bug at present, because there is only one other schema, and the fallback mechanism selects the most recent. However, for good practice we should still register the draft 6 schema.
This PR adds a `Validator.ID_OF` staticmethod, and call it from the registrar.

Fix bug in current registration of validators and address #417

---

jsonschema/tests/test_validators.py
jsonschema/validators.py

The resource used by `urlopen` was never explicitly closed, running an app with pythons `-W all` flag raised loads of `ResourceWarning`s. Using a context manager is a simple fix.

Fix unclosed resource in validators

---

jsonschema/compat.py

"`from collections import MutableMapping, Sequence`" produces a `DeprecationWarning` under Python 3.7 with the message:
> Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
This patch eliminates this warning by preferring to import from `collections.abc` first, falling back to `collections` only if that fails (i.e., if running under Python < 3.3).

Prefer importing ABCs from collections.abc

---

README.rst
json/bin/jsonschema_suite

The old URLs would redirect to the updated ones anyway.

Updated PyPI URLs

---

.gitignore
jsonschema/tests/test_validators.py
jsonschema/validators.py

This addresses this issue #460 
Followed your lead by using the `SynchronousTestCase` . Any reason or particular features that drive using it instead of just `TestCase`?
Please let me know if you have any comments. Can't think of any other bright ideas regarding the warnings. First time using the module :) and feels like a pretty small PR so maybe I am missing something.

Add a deprecation warning to validate_for if schema doesn't exist

---

README.rst

This PR adds the `Installation` section to the README as written in #488.

Add installation instructions to README: Issue #488

---

jsonschema/exceptions.py
jsonschema/tests/test_exceptions.py
jsonschema/tests/test_validators.py

This PR addresses #477.
Currently, `ValidationError` and `SchemaError` implement `__eq__`, but don't implement `__hash__`, which makes then unhashable.  That prevents them from being used in certain scenarios, notably in a test suite that uses `pytest` [Edit: It fails under python 3.6, but not 3.7].
The easiest way to make them hashable is to simply remove the `__eq__` implementation.  I doubt many users of `jsonschema` rely on the fact that those errors are comparable.
The only problem is jsonschema's own test suite, which *does* rely on `ValidationError.__eq__()`.  But that's easy to change, as I've done in this PR.  Thoughts?

Make exceptions hashable (but not comparable)

---

setup.cfg

`pkg_resources` requires `setuptools`.  Fixes #510

Depend on setuptools

---

docs/jsonschema_role.py
docs/requirements.txt

Exploring possibilities of collaboration, a following up on [this conversation at #470](https://github.com/Julian/jsonschema/issues/470#issuecomment-453289512), I found out that I could not build the documentation on my laptop, running macOS with vanilla installations of CPython 3.6 and 3.7 from www.python.org.
The failure is in the `docs/jsonschema_role.py` Sphix extension, in the `fetch_or_load` function, which uses `urllib.request.urlopen` with an HTTPS URL. Unfortunately, such CPython installs fail to validate server-side TLS certificates.
The motive stems from the fact that, as stated in the installer's README, a private OpenSSL copy is included in the distribution which does not use the system certificate store for validation; instead, the suggested approach is doing a system-wide …

Docs now build successfully out of the box on macOS CPython.

---

jsonschema/tests/test_validators.py
jsonschema/validators.py

Hi,
`id_of` was added to `create` in 3.0.0, but it was forgotten from `extend`.

Add missing id_of to validators.extend

---

jsonschema/cli.py
jsonschema/tests/test_cli.py
tox.ini

Added for this: https://github.com/Julian/jsonschema/issues/621
Can now do something like this:
`cat test.json | jsonschema test.schema`

Get input from commandline when instance(s) not provided

---

setup.cfg

Currently, it's not possible to install jsonschema offline, as pip cannot found setup_requires dependencies.
See https://www.scivision.dev/setuptools-pyproject-toml-offline/ and https://stackoverflow.com/questions/27307082/install-package-which-has-setup-requires-from-local-source-distributions.
Simply removing the option from setup.cfg do the trick.

Avoid setup_requires offline installation issues

---

docs/errors.rst
jsonschema/exceptions.py
jsonschema/tests/test_validators.py

Add support to have the offending element within the instance reported via a [JSON path](https://goessner.net/articles/JsonPath/index.html)
This allows to have a "standard" way of identifying the element with the problem, that can be used by other external CLI tools for example.

add json_path error attribute

---

README.rst
tox.ini

Resolves #689 
This PR removes the instructions for manually running the pyperf benchmarks from `README.rst`. It also fixes the tox environment (`tox -e perf`) for running the benchmarks, which was missing a dependency on twisted.

WIP: Remove outdated benchmarking instructions.

---

.github/workflows/ci.yml
docs/conf.py
json/bin/jsonschema_suite
jsonschema/cli.py
jsonschema/validators.py
setup.cfg
tox.ini

Allowing to drop six requirement

[compat] Drop support of PY2

---

jsonschema/cli.py
jsonschema/tests/test_cli.py

As commented in https://github.com/Julian/jsonschema/issues/710#issuecomment-676851156.
By adjusting the position of `arguments["validator"]`, we can solve this bug, but because `arguments["validator"]` is not processed in `parse_args`, it will cause the `test_latest_validator_is_the_default` test case to fail, so I deleted this test case.

Fix cli bug about getting arguments["validator"].

---

README.rst

@Julian https://notebooks.ai/ service will no longer be available. We should remove the demo link from the README file because it will stop working in October 2020.

notebooks.ai is shutting down - Remove demo link from README file

---

jsonschema/_validators.py
jsonschema/tests/test_jsonschema_test_suite.py

Fixes https://github.com/Julian/jsonschema/issues/743, by falling back to use of `Fraction`s on float overflow.
This passes both the required and the optional test from https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/438

Handle `multipleOf` overflow

---

jsonschema/tests/fuzz_validate.py

The current fuzzer is broken with 
```
File "hypothesis/core.py", line 919, in fuzz_one_input
AttributeError: 'HypothesisHandle' object has no attribute '_HypothesisHandle__cached_target'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "jsonschema/tests/fuzz_validate.py", line 47, in <module>
File "jsonschema/tests/fuzz_validate.py", line 40, in main
File "hypothesis/core.py", line 921, in fuzz_one_input
File "hypothesis/core.py", line 1174, in _get_fuzz_target
File "hypothesis/core.py", line 441, in process_arguments_to_given
File "hypothesis/strategies/_internal/strategies.py", line 377, in validate
File "hypothesis/strategies/_internal/collections.py", line 41, in do_validate
File …
```

Fix fuzzer

---

jsonschema/_format.py
setup.cfg

Fixes the validation of `uri-template` using https://pypi.org/project/uri-template/

Fixes validation for uri-template format

---

.github/workflows/coverage.yml
jsonschema/_format.py

Move coverage pipeline from PyPy (which currently implements Python 3.6) to CPython with Python 3.9.

Use python 3.9 for coverage

---

jsonschema/benchmarks/issue232.py
jsonschema/benchmarks/json_schema_test_suite.py

When packaging jsonschema and poetry-core (which bundles it) in Fedora, we have
realised that there are nonexecutable files with a shebang line.
It seems that the primary purpose of these files is to be imported from Python code
and hence the shebangs appear to be unnecessary.
Shebangs are hard to handle when doing downstream packaging, because it makes
sense for upstream to use `#!/usr/bin/env` python while in the RPM package,
we need to avoid that and use a more specific interpreter. Since the
shebangs were unused, I propose to remove them to avoid problems.

Remove shebangs from nonexecutable scripts

---

.gitignore
setup.cfg

Universal wheels are for when you need to support both Python 2 and 3:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels
Before:
* `jsonschema-0.1.dev1+gdbda4f7-py2.py3-none-any.whl`
After:
* `jsonschema-0.1.dev2+g97057ed-py3-none-any.whl`
---
Also ignore some build dirs generated by running `python -m build` locally.

Don't build universal wheels for Python 3-only

---

CHANGELOG.rst

It was dropped in https://github.com/Julian/jsonschema/commit/3fb0576411701b57899cf9c812e32046ddc2adf9

Add release note about dropping support for Py 3.6

---

jsonschema/_utils.py
setup.cfg

Fixes https://github.com/Julian/jsonschema/issues/871.

Load schemas via importlib.resources

---

jsonschema/_utils.py
jsonschema/tests/test_jsonschema_test_suite.py

Fixes #866
Changes proposed in this PR:
- Revert ed4693ca07c912f7640997f67401d31076959081 to restore skipped tests.
- Fix bug in `_utils.uniq()` function where the function would return (True) early if the first two items of the array are unique, preventing verification of other array items.

Ensure all elements of arrays are verified for uniqueness

---

setup.cfg

Based on this recent [change in the docs](https://github.com/python/importlib_resources/commit/ed3b2d30e01121b27a6e0d0a8a478a483e437736) I opted to require `importlib_resources>=1.4.0`, but tests also passed in jsonschema when using importlib_resources v1.1.0.
Let me know if you want to use `importlib_resources>=1.1.0` instead.
For reference: https://importlib-resources.readthedocs.io/en/latest/history.html.
Fixes https://github.com/Julian/jsonschema/issues/876.

Add version constraint to importlib_resources

---

CHANGELOG.rst
jsonschema/_utils.py

Hi!
I noticed, that the `uniq` implementation uses `_sequence_equal` if the input is sortable. Then, if e.g. `[1, 2, 3, 4, 5]` is passed to `uniq`, then it falls back to brute force because on the first loop iteration `_sequence_equal` fails with `TypeError: object of type 'int' has no len()`, but it should not as a list of ints is sortable & straightforward to compare.
Code sample:
```python
CONTAINER = list(range(100))
assert uniq(CONTAINER)
assert not uniq([1, 1])
start = time.perf_counter()
for _ in range(1000):
uniq(CONTAINER)
print(time.perf_counter() - start)
```
Before: 5.4033913369985385s
After: 0.12076822199924209s
I didn't check whether this was the direct cause of #853, but hopefully, it can improve the status quo :)
**Update**: The change doesn't affect #853 much (measured by …

perf: Undesired fallback to brute force container uniqueness check on certain input types

---

README.rst
docs/creating.rst
docs/errors.rst
docs/faq.rst
docs/spelling-wordlist.txt
docs/validate.rst
jsonschema/__init__.py
jsonschema/_types.py
jsonschema/protocols.py
jsonschema/tests/test_validators.py
jsonschema/validators.py
setup.cfg

I'm marking this as a draft. I wanted to share what I've got so far for #548, but I'm not certain that it's good to merge without checking in on typeshed to see what we should do there.
---
This is a Protocol implementation for type checking under mypy and other static analyzers. It uses the protocol class defined in py3.8+ and uses typing_extensions as a backport for py3.7
The documentation-only validator class has been replaced with the protocol, and docs are now driven via autoclass on the protocol.
Importantly, several documented methods of the class have been removed, as they were marked deprecated under jsonschema v3.0 and are no longer provided by the builtin validators.
Minor adjustments to the docs are made to repoint references at the new class definition.

Add `jsonschema.protocols.IValidator`

---

CHANGELOG.rst
jsonschema/validators.py

The latest commit cuts the time to 8.08942461013794 sec which is quite close to `3.2.0` version performance (5.38702654838562 sec on my machine)

perf: Cache reference lookups for subschemas

---

jsonschema/validators.py

Continuation of #894. This patch introduces a cache for subschemas-related keywords, which reduces the number of calls to the search routine. All subschemas-related keywords are searched in one pass and then stored in a cached dict. With the OP from #893 it reduces the total number of function calls from 61512655 to 56438634 (~9%). The number of calls to the search routine is reduced 5x (from 1090000 to 218000).
I'd be happy to know what do you think :)

perf: Cache subschemas

---

jsonschema/__init__.py
jsonschema/tests/test_deprecations.py
jsonschema/validators.py

Currently the warning location points inside the `jsonschema` code and it takes an additional effort to find where the actual code that triggers it is located.

Move warnings to user context

---

.coveragerc
.github/workflows/ci.yml
docs/requirements.txt
jsonschema/_format.py
jsonschema/_types.py
jsonschema/_utils.py
jsonschema/cli.py
jsonschema/exceptions.py
jsonschema/protocols.py
jsonschema/tests/test_cli.py
jsonschema/tests/test_validators.py
jsonschema/validators.py
setup.cfg
tox.ini

This is the smallest possible change to get mypy passing on the jsonschema codebase. The goal of this configuration is to enforce type annotations anywhere that they appear.
That is, if a method is added to the codebase,
def foo(x: int) -> str:
return str(x)
then usages of `foo` will by type checked. If no annotations are added, `mypy` will not type check functions.
For the most part, this keeps the impact low. The one exceptional case is the use of `pyrsistent.pmap` as an argument to `attr.ib(converter=...)`. Unfortunately, it causes `mypy` to incorrectly deduce the type of the init parameter created by attrs. We need to "explain the type of init" to mypy by creating a callable with a concrete type to act as the converter. The callable in question simply wraps `pmap` with a cast and …

Setup mypy in `tox -e typing` and get it to pass

---

jsonschema/_utils.py
jsonschema/_validators.py
jsonschema/tests/test_jsonschema_test_suite.py
jsonschema/validators.py

The description in https://stackoverflow.com/a/69774520/5382179 helped me better understand how the keyword should actually work and the PR extends the missing parts of the current implementation of the keyword.
There might be a better way to implement this, but it would require bigger changes in the way the scopes and the validator functions are handled.

Extend dynamicRef keyword

---

.gitignore
jsonschema/protocols.py
jsonschema/validators.py

Implement an FORMAT_CHECKER attribute for the Validator class. This allows to use the `format_checker` of an automatically detected validator like so:
```python
from jsonschema.validators import validator_for
Validator = validator_for(schema)
Validator(schema, format_checker=Validator.FORMAT_CHECKER).validate(instance)
```

Add FORMAT_CHECKER attribute for Validator

---

jsonschema/cli.py

The help-string for --error-format is triple-quoted, so remove unnecessary quote character

Remove stray double-quote

---

jsonschema/_utils.py
jsonschema/tests/test_validators.py

Fixes problem where error message was not consistent between runs, even when the inputs were the same (file to be validated and the schema to use).
This should make the outcomes predictable and eliminate the random factor from it. In fact the sorting already happens in 3 other places inside the library but that specific location was missed.
This was found while working on https://github.com/ansible/ansible-lint/pull/2035 and where we observed that the output did very randomly between two runs:
```
"Additional properties are not allowed ('when', 'pki_certificates', 'pki_realms', 'pki_authorities', 'pki_private_groups_present', 'pki_routes' were unexpected)"
"Additional properties are not allowed ('pki_private_groups_present', 'when', 'pki_authorities', 'pki_certificates', 'pki_realms', …
```

Ensure proper sorting of list in error message

---

jsonschema/_validators.py
jsonschema/tests/test_jsonschema_test_suite.py
jsonschema/tests/test_validators.py

Fixes attribute error when trying to validate `unevaluatedProperties` and `unevaluatedItems` on objects which aren't a `dict` or `list` respectively.

Only validate unevaluated properties/items on applicable types

---

setup.cfg

Avoids problems with mypy by officially declaring the library as typed.
> Skipping analyzing "jsonschema": module is installed, but missing library stubs or py.typed marker
See: https://peps.python.org/pep-0561/

Mark library as typed (PEP-561)

---

jsonschema/tests/fuzz_validate.py

I noticed the fuzzer has been broken for a while (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37327) and this should fix it. It's related to some updates in Atheris -- I believe since this commit https://github.com/google/atheris/commit/0fb69ecd1f3cff719e21cf4d2b7e2cb7fb949f49
Another interesting update on the OSS-Fuzz side is that it now builds with code coverage. So once the fuzzer starts running again we should be able to see visualise how much of the code has been explored (by visiting https://oss-fuzz.com).

Fix fuzzer to include instrumentation

---

jsonschema/_reflect.py
jsonschema/tests/_suite.py

There are small typos in:
- jsonschema/_reflect.py
- jsonschema/tests/_suite.py
Fixes:
- Should read `dynamically` rather than `dynamicallly`.
- Should read `distinguish` rather than `distiguish`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

CHANGELOG.rst
jsonschema/exceptions.py
jsonschema/tests/test_exceptions.py
jsonschema/validators.py

Enhance best match to prefer errors from matching types.

---

docs/conf.py
docs/creating.rst
docs/errors.rst
docs/faq.rst
docs/index.rst
docs/references.rst
docs/requirements.in
docs/requirements.txt
docs/spelling-wordlist.txt
docs/validate.rst
jsonschema/__init__.py
jsonschema/protocols.py
jsonschema/validators.py

Cleanup of the regular pages will come after.
----
:books: Documentation preview :books:: https://python-jsonschema--989.org.readthedocs.build/en/989/

Enable dedicated API documentation page(s)

---

jsonschema/exceptions.py

To show what I mean with putting a class "in between" the main `_Error` class and the classes that actually have the attribute that is being used in `__str__`. This satisfies type checkers and has minimal runtime impact, while making the code a bit cleaner.
Let me know if this is something you would consider!
----
:books: Documentation preview :books:: https://python-jsonschema--1022.org.readthedocs.build/en/1022/

Add annotations for `_Error`

---

jsonschema/_format.py

Python 3.11 and later allow additional ISO8601 formats in `datetime` module ISO8601 parsing. These formats are not RFC3339 section 5.6 compliant.
Especially `datetime.date.fromisoformat()` now allows strings like:
* `20230328` (2023-03-28)
* `2022W527` (2023-01-01)
* `2023-W01` (2023-01-02)
* `2023-W13-2` (2023-03-28)
Fix by doing a regular expression check before passing the value to `datetime` module. This made the original `.isascii()` check unnecessary.
See:
* https://docs.python.org/3/whatsnew/3.11.html#datetime
* https://github.com/python/cpython/commit/1303f8c927
* https://docs.python.org/3.11/library/datetime.html#datetime.date.fromisoformat
* https://www.rfc-editor.org/rfc/rfc3339#section-5.6
Tests covering the invalid values to be sent to json-schema-org/JSON-Schema-Test-Suite …

fix: Python 3.11 date.fromisoformat() allows extra formats

---

jsonschema/_utils.py

It appears that without checking `is_valid` the test suite still passes. The invalid properties already produce an error, so that the "unevaluated property" error is never _needed_ to achieve a validation failure. On the contrary, when all property validation succeeds, "unevaluated property" could still produce an error.
Arguably, producing an error for expected but invalid properties is also confusing, being a "double jeopardy" of validation failures.
----
:books: Documentation preview :books:: https://python-jsonschema--1075.org.readthedocs.build/en/1075/

Do not validate for unevaluatedProperties

---

jsonschema/_format.py

When validating hostname format strings with module fqdn, only FQDNs were accepted, as the minimum label length of the FQDN class is 2. Therefore, single label hostnames like "localhost" were rejected.
Fixed this by validating with a minimum label length of 1.
- Tests: json-schema-org/JSON-Schema-Test-Suite#685
- Fixes: python-jsonschema/jsonschema#1162
----
:books: Documentation preview :books:: https://python-jsonschema--1164.org.readthedocs.build/en/1164/

Allow single label hostname in format string

---

jsonschema/_keywords.py

The following schema accepts the instance although it should be rejected:
```python
from jsonschema import validate
schema = {
"enum": [
[False]
],
"$schema": "https://json-schema.org/draft/2020-12/schema"
}
instance = [0]
validate(instance, schema)  # erroneously accepts the instance
```
I guess, this is caused by the following line:
https://github.com/python-jsonschema/jsonschema/blob/256dadd3539861ae696c03805923eb4097b871f9/jsonschema/_keywords.py#L271
(`[0] in [[False]]` is true, so `[0] not in [[False]]` is false)
----
📚 Documentation preview 📚: https://python-jsonschema--1208.org.readthedocs.build/en/1208/

Wrong behaviour for enum keyword

---

jsonschema/_utils.py
jsonschema/tests/test_utils.py

This addresses #1223 
----
📚 Documentation preview 📚: https://python-jsonschema--1224.org.readthedocs.build/en/1224/

Check for identity before equality when comparing objects with `equal` (used in a number of keywords)

---

jsonschema/exceptions.py

After getting the go-ahead in https://github.com/python-jsonschema/jsonschema/issues/1017 I thought I would test the waters both in size and scope of potential PRs.
Feel free to ask me to separate some of the commits into separate PRs. I thought this was quite manageable, especially if you go commit by commit.
----------------------
I thought I would start with a fairly self contained module (_and a module I interact with quite a lot with at work myself_).
I think most of the changes are pretty straight forward. The first commit is hardest to review and for now I focused on the attributes that I was most sure about, keeping harder ones for later.
The second and third commit "fix issues". I understand that these are not actual issues and that through the dynamicness of Python these code …

Add some typing to the ``exceptions.py`` module

---

docs/referencing.rst

I was running into this and thought it would be useful to have a link to how check-jsonschema handles it.
----
📚 Documentation preview 📚: https://python-jsonschema--1326.org.readthedocs.build/en/1326/

docs: add link to check-jsonschema for how to handle generic yaml parsing

---

jsonschema/exceptions.py
jsonschema/tests/test_exceptions.py
noxfile.py

This PR introduces the following change:
* Unambiguously quote and escape properties in JSON path rendering
Using the script from #1389, this is the new output with the changes in this branch:
```shell
$ python demo.py 
property=''             json_path="$['']"
property='['            json_path="$['[']"
property='.'            json_path="$['.']"
property='\\'           json_path="$['\\\\']"
property="'"            json_path="$['\\'']"
property=' '            json_path="$[' ']"
property='"'            json_path='$[\'"\']'
property='a[0]'         json_path="$['a[0]']"
```
Fixes #1389
----
📚 Documentation preview 📚: https://python-jsonschema--1390.org.readthedocs.build/en/1390/

Unambiguously quote and escape properties in JSON path rendering

---

jsonschema/benchmarks/import_benchmark.py
jsonschema/tests/test_validators.py
jsonschema/validators.py

The goal with this PR is to help reduce the time required to import the jsonschema module.
On my end calling:
`python -X importtime -c "import jsonschema"`
* Before: 216ms (main)
* After: 173ms (this PR)
----
<details>
<summary>importtime output (main)</summary>
```
import time: self [us] | cumulative | imported package
import time:       120 |        120 | winreg
import time:       163 |        163 |   _io
import time:        38 |         38 |   marshal
import time:       165 |        165 |   nt
import time:       628 |        992 | _frozen_importlib_external
import time:       930 |        930 |   time
import time:       266 |       1195 | zipimport
import time:        51 |         51 |     _codecs
import time:       543 |        593 |   codecs
import time:      1275 |       1275 | …
```

validators: avoid `urllib.request` at import-time
